import './globals.scss'

import { Mulish } from 'next/font/google'
const inter = Mulish({ subsets: ['latin'] })

import App from './components/App'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="" style={{ colorScheme: '' }}>
      <body className={inter.className}>
        <App>{children}</App>
      </body>
    </html>
  )
}
